name: dask
channels:
  - conda-forge
dependencies:
  - python-graphviz
  - python=3.8
  - pip
  - distributed=2.20.0
  - scikit-learn[version='>=0.22.1']
  - scikit-image
  - cachey
  - dask-labextension[version='>=2.0.0']
  - scikit-image[version='>=0.15.0']
  - nodejs
  - pandas-datareader
  - ipywidgets[version='>=7.5']
  - fastparquet
  - toolz
  - bokeh[version='>=2.0.0']
  - jupyterlab[version='>=2.0.0']
  - dask=2.20.0
  - ujson
  - notebook
  - matplotlib
  - s3fs
  - dask-core
  - pandas[version='>=1.0.1']
  - numpy[version='>=1.18.1']
  - dask-ml
  - dask-glm
  - scipy[version='>=1.3.0']
  - h5py
